### ISSUE TITLE
运行到chmod +x ./init-letsencrypt.sh这个命令时提示No such file or directory

### ISSUE THREAD

**Issue by xday2000** [aitlp/docker-v2ray#2]
这个文件在docker-v2ray路径下有，但是貌似这样直接用会找不到，怎么办？

linux小白，不懂docker，求大佬指教

**Comment by xday2000** [comment]
在docker-v2ray目录下直接运行通过了。但是不知道如何配置v2rayN客户端，在网上找了教程填写了host和路径仍然不能使用。目前不能确定是配置问题还是安装过程问题

总之先试试其它方法

**Comment by aitlp** [comment]
已解决，详见readme.
