### ISSUE TITLE
Challenge failed for domain

### ISSUE THREAD

**Issue by Longxr** [aitlp/docker-v2ray#4]
终端提示：
```shell
Challenge failed for domain xxx
http-01 challenge for xxx
Cleaning up challenges
Some challenges have failed.
```

查看logs/nginx/error.log，提示：error:2006D080:BIO routines:BIO_new_file:no such file)
并且在data/certbot/conf/live目录下开始有fullchain.pem生成，在运行出现错误提示后live目录就被清空了

**Comment by Longxr** [comment]
不使用脚本注册，在阿里云买域名配置DV免费证书后，docker-compose.yml可用

**Comment by aitlp** [comment]
> 终端提示：
> 
> ```shell
> Challenge failed for domain xxx
> http-01 challenge for xxx
> Cleaning up challenges
> Some challenges have failed.
> ```
> 
> 查看logs/nginx/error.log，提示：error:2006D080:BIO routines:BIO_new_file:no such file)
> 并且在data/certbot/conf/live目录下开始有fullchain.pem生成，在运行出现错误提示后live目录就被清空了

一般是跟nginx配置有关系

**Comment by Longxr** [comment]
> > 终端提示：
> > ```shell
> > Challenge failed for domain xxx
> > http-01 challenge for xxx
> > Cleaning up challenges
> > Some challenges have failed.
> > ```
> > 
> > 
> > 查看logs/nginx/error.log，提示：error:2006D080:BIO routines:BIO_new_file:no such file)
> > 并且在data/certbot/conf/live目录下开始有fullchain.pem生成，在运行出现错误提示后live目录就被清空了
> 
> 一般是跟nginx配置有关系

应该不是，我就修改了自己下载好的证书路径就可以正常使用了，应该是自动注册时没申请到，不知道是不是因为我的域名在阿里云申请过ssl证书的原因_(:з)∠)_
