### ISSUE TITLE
容器运行失败

### ISSUE THREAD

**Issue by haohowey** [aitlp/docker-v2ray#5]
如题，在centos8上，容器运行不起来

**Comment by aitlp** [comment]
错误信息？

**Comment by haohowey** [comment]
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for your_domain.com
Using the webroot path /var/www/certbot for all unmatched domains.
Waiting for verification...
Challenge failed for domain your_domain.com
http-01 challenge for your_domain.com
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: your_domain.com
   Type:   connection
   Detail: Fetching
   http://your_domain.com/.well-known/acme-challenge/J4bq98GSm5wm-5ZmI5yoDh_A3ST8rBwcWuy7NjkU2FY:
   Connection refused

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.

### Reloading nginx ...
Error response from daemon: Container 4ec7622ddb8680d2a527755f59259a81adfbae093dab0a821be925032319bbae is restarting, wait until the container is running

**Comment by haohowey** [comment]
这次是在debian10上运行的

**Comment by haohowey** [comment]
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/your_domain/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/your_domain/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/your_domain/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/your_domain/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/your_domain/fullchain.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/your_domain/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

查了一下docker nginx的日志信息

**Comment by haohowey** [comment]
我发现之前有人也报告过这个问题，也没得到解决，看来不是我的配置问题

**Comment by aitlp** [comment]
已解决此问题。
